import express from "express";
import { createServer as createViteServer } from "vite";
import path from "path";
import { fileURLToPath } from "url";
import dotenv from "dotenv";
import crypto from "crypto";

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // --- Elite State Mock (To be synced with Supabase in Production) ---
  const IMPERIAL_DB = {
    escrowOrders: [] as any[],
    autoGeneratedTemplates: [] as any[],
    marketDemand: 1.0 // Base demand factor
  };

  // 1. Premium Payment Engine: NOWPayments Integration
  app.post("/api/payments/create", async (req, res) => {
    const { price_amount, price_currency, order_id, templateId } = req.body;
    const apiKey = process.env.NOWPAYMENTS_API_KEY;

    try {
      if (!apiKey || apiKey === "your_api_key_here") {
        return res.status(500).json({ 
          error: "بوابة الدفع غير مهيأة", 
          details: "يجب عليك إضافة مفتاح NOWPAYMENTS_API_KEY في إعدادات البيئة (Secrets) لتمكين الدفع الحقيقي بالعملات الرقمية." 
        });
      }

      const response = await fetch("https://api.nowpayments.io/v1/invoice", {
          method: "POST",
          headers: {
            "x-api-key": apiKey,
            "Content-Type": "application/json"
          },
          body: JSON.stringify({
            price_amount: price_amount,
            price_currency: price_currency || "usd",
            order_id: order_id,
            order_description: `Elite Asset Purchase: ${templateId || 'assets'}`,
            ipn_callback_url: `${req.protocol}://${req.get('host')}/api/payments/webhook`,
            success_url: `${req.protocol}://${req.get('host')}/success`,
            cancel_url: `${req.protocol}://${req.get('host')}/cancel`
          })
      });

      const data = await response.json();
      
      if (!response.ok) {
        return res.status(500).json({ error: "خطأ في إنشاء الفاتورة", details: data.message || "حدث خطأ غير متوقع مع بوابة الدفع" });
      }

      if (data.invoice_url) {
         const holdTime = 7 * 24 * 60 * 60 * 1000;
         IMPERIAL_DB.escrowOrders.push({
           id: data.id,
           orderId: order_id,
           templateId,
           amount: price_amount,
           status: 'pending',
           createdAt: Date.now(),
           unlockAt: Date.now() + holdTime,
           commission: 0.05
         });
         return res.json({ invoice_url: data.invoice_url });
      } else {
         return res.status(500).json({ error: "فشل إنشاء الفاتورة", details: "بوابة الدفع لم تعد رابط الفاتورة" });
      }

    } catch (error) {
       res.status(500).json({ error: "انقطع الاتصال الأساسي ببوابة الدفع", details: (error as Error).message });
    }
  });

  // Webhook Listener (IPN) with Signature Verification
  app.post("/api/payments/webhook", (req, res) => {
    const ipnSecret = process.env.NOWPAYMENTS_IPN_SECRET;
    const receivedSig = req.headers['x-nowpayments-sig'];
    
    if (ipnSecret && receivedSig) {
      const payload = JSON.stringify(req.body, Object.keys(req.body).sort());
      const hmac = crypto.createHmac('sha512', ipnSecret);
      hmac.update(payload);
      const signature = hmac.digest('hex');
      
      if (signature !== receivedSig) {
        console.error("[WEBHOOK] Signature Validation Failed");
        return res.status(400).send("Invalid Signature");
      }
    }

    const { payment_status, order_id, invoice_id } = req.body;

    if (payment_status === 'finished' || payment_status === 'confirmed') {
       const order = IMPERIAL_DB.escrowOrders.find(o => o.id === invoice_id || o.orderId === order_id);
       if (order) {
         order.status = 'confirmed';
         console.log(`[PAYMENT] Order ${order_id} confirmed by Webhook.`);
       }
    }

    res.sendStatus(200);
  });

  // 2. Autonomous Generation Engine (Pulse Cron)
  app.post("/api/cron/pulse", async (req, res) => {
    console.log("[CRON] Elite Pulse: Harvesting New Premium Assets...");
    
    try {
      // Simulation of MiniMax M2.7 Generation
      const generationOutput = {
        title: `Elite Concept ${Math.floor(Math.random() * 999)}`,
        price: 39 + Math.floor(Math.random() * 100),
        category: 'ai-startup',
        confidenceScore: 98.4
      };

      IMPERIAL_DB.autoGeneratedTemplates.push(generationOutput);

      // Escrow Release Check
      const now = Date.now();
      let releasedCount = 0;
      IMPERIAL_DB.escrowOrders.forEach(order => {
        if (order.status === 'pending' && now >= order.unlockAt) {
          order.status = 'released';
          releasedCount++;
        }
      });

      res.json({ 
        status: "Pulse Synchronized", 
        newAsset: generationOutput,
        releasedEscrows: releasedCount 
      });
    } catch (error) {
      res.status(500).json({ status: "Pulse Synchronization Error" });
    }
  });

  // 3. Neuro-Pricing Engine (72h Adaptive Pricing)
  app.post("/api/cron/neuro-pricing", (req, res) => {
    // Neural logic: increase demand factor slightly to simulate market growth
    IMPERIAL_DB.marketDemand *= (1 + (Math.random() * 0.1));
    console.log(`[CRON] Elite Neuro-Pricing: Demand Factor now at ${IMPERIAL_DB.marketDemand.toFixed(2)}`);
    res.json({ status: "Market Calibrated", demandFactor: IMPERIAL_DB.marketDemand });
  });

  // API Routes
  app.get("/api/health", (req, res) => {
    res.json({ status: "Elite Systems Operational", timestamp: new Date().toISOString() });
  });

  // Secure Proxy for OpenRouter (MiniMax M2.7)
  app.post("/api/elite-forge", async (req, res) => {
    const apiKey = process.env.OPENROUTER_API_KEY;
    if (!apiKey) {
      return res.status(500).json({ error: "OPENROUTER_API_KEY not configured in Elite Vault" });
    }

    try {
      const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${apiKey}`,
          "HTTP-Referer": "https://empire.ais.run",
          "X-Title": "Template Empire",
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          model: "minimax/minimax-01", // Representing MiniMax M2.7 as best available
          messages: [
            { role: "system", content: "أنت محرك التوليد الإمبراطوري. قم بتوظيف نموذج MiniMax M2.7 لابتكار أصل رقمي سيادي." },
            { role: "user", content: "توليد مفهوم أصل رقمي فاخر لعام 2126." }
          ]
        })
      });

      const data = await response.json();
      res.json(data);
    } catch (error) {
      res.status(500).json({ error: "Quantum Link Failure", detail: error });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  // Simulation of Autonomous Empire Behavior (Periodic Pulse)
  setInterval(async () => {
    console.log("[AUTO-PULSE] Breathing through the Void...");
    try {
      // Simulate escrow release or internal recalibration
      const now = Date.now();
      IMPERIAL_DB.escrowOrders.forEach(order => {
        if (order.status === 'pending' && now >= order.unlockAt) {
          order.status = 'released';
        }
      });
    } catch (e) {}
  }, 60000); // Every 60 seconds for preview liveliness

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Elite Authority established at http://localhost:${PORT}`);
  });
}

startServer();
