import { Template } from './types';

// Real World Premium Example Templates / Frameworks represented as Premium Assets
// Utilizing incredibly high-end, dark, liquid, or cosmic images to maintain the Kyrosys aesthetic
export const TEMPLATES: Template[] = [
  {
    "id": "2095",
    "title": "Level",
    "category": "Business",
    "price": 49,
    "originalPrice": 69,
    "image": "https://templatemo.com/screenshots/full-template-2095-level.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-2095-level.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/2095_level.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "حصري",
    "valueProposition": "استثمر في قالب Level ووفر عشرات الساعات من التطوير.",
    "rating": 4.5,
    "reviews": 100,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "2097",
    "title": "Pop",
    "category": "Portfolio",
    "price": 59,
    "originalPrice": 79,
    "image": "https://templatemo.com/screenshots/full-template-2097-pop.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-2097-pop.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/2097_pop.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Pop ووفر عشرات الساعات من التطوير.",
    "rating": 4.6,
    "reviews": 107,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "2110",
    "title": "Character",
    "category": "SaaS",
    "price": 69,
    "originalPrice": 89,
    "image": "https://templatemo.com/screenshots/full-template-2110-character.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-2110-character.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/2110_character (1).zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Character ووفر عشرات الساعات من التطوير.",
    "rating": 4.7,
    "reviews": 114,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "2117",
    "title": "Infinite Loop",
    "category": "Landing",
    "price": 79,
    "originalPrice": 99,
    "image": "https://templatemo.com/screenshots/full-template-2117-infinite-loop.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-2117-infinite-loop.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/2117_infinite_loop (1).zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Infinite Loop ووفر عشرات الساعات من التطوير.",
    "rating": 4.8,
    "reviews": 121,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "480",
    "title": "Story",
    "category": "E-commerce",
    "price": 89,
    "originalPrice": 109,
    "image": "https://templatemo.com/screenshots/full-template-480-story.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-480-story.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_480_story.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Story ووفر عشرات الساعات من التطوير.",
    "rating": 4.9,
    "reviews": 128,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "481",
    "title": "Elevate",
    "category": "Business",
    "price": 49,
    "originalPrice": 69,
    "image": "https://templatemo.com/screenshots/full-template-481-elevate.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-481-elevate.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_481_elevate.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Elevate ووفر عشرات الساعات من التطوير.",
    "rating": 4.5,
    "reviews": 135,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "482",
    "title": "Strip",
    "category": "Portfolio",
    "price": 59,
    "originalPrice": 79,
    "image": "https://templatemo.com/screenshots/full-template-482-strip.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-482-strip.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_482_strip.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Strip ووفر عشرات الساعات من التطوير.",
    "rating": 4.6,
    "reviews": 142,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "483",
    "title": "Lumino",
    "category": "SaaS",
    "price": 69,
    "originalPrice": 89,
    "image": "https://templatemo.com/screenshots/full-template-483-lumino.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-483-lumino.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_483_lumino.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Lumino ووفر عشرات الساعات من التطوير.",
    "rating": 4.7,
    "reviews": 149,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "484",
    "title": "Ocean",
    "category": "Landing",
    "price": 79,
    "originalPrice": 99,
    "image": "https://templatemo.com/screenshots/full-template-484-ocean.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-484-ocean.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_484_ocean.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Ocean ووفر عشرات الساعات من التطوير.",
    "rating": 4.8,
    "reviews": 156,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "485",
    "title": "Rainbow",
    "category": "E-commerce",
    "price": 89,
    "originalPrice": 109,
    "image": "https://templatemo.com/screenshots/full-template-485-rainbow.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-485-rainbow.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_485_rainbow.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Rainbow ووفر عشرات الساعات من التطوير.",
    "rating": 4.9,
    "reviews": 163,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "486",
    "title": "New Event",
    "category": "Business",
    "price": 49,
    "originalPrice": 69,
    "image": "https://templatemo.com/screenshots/full-template-486-new-event.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-486-new-event.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_486_new_event.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "حصري",
    "valueProposition": "استثمر في قالب New Event ووفر عشرات الساعات من التطوير.",
    "rating": 4.5,
    "reviews": 170,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "487",
    "title": "Fitness",
    "category": "Portfolio",
    "price": 59,
    "originalPrice": 79,
    "image": "https://templatemo.com/screenshots/full-template-487-fitness.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-487-fitness.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_487_fitness.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Fitness ووفر عشرات الساعات من التطوير.",
    "rating": 4.6,
    "reviews": 177,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "488",
    "title": "Classic",
    "category": "SaaS",
    "price": 69,
    "originalPrice": 89,
    "image": "https://templatemo.com/screenshots/full-template-488-classic.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-488-classic.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_488_classic.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Classic ووفر عشرات الساعات من التطوير.",
    "rating": 4.7,
    "reviews": 184,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "489",
    "title": "Strategy",
    "category": "Landing",
    "price": 79,
    "originalPrice": 99,
    "image": "https://templatemo.com/screenshots/full-template-489-strategy.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-489-strategy.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_489_strategy.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Strategy ووفر عشرات الساعات من التطوير.",
    "rating": 4.8,
    "reviews": 191,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "490",
    "title": "Comila",
    "category": "E-commerce",
    "price": 89,
    "originalPrice": 109,
    "image": "https://templatemo.com/screenshots/full-template-490-comila.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-490-comila.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_490_comila.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Comila ووفر عشرات الساعات من التطوير.",
    "rating": 4.9,
    "reviews": 198,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "491",
    "title": "Flat",
    "category": "Business",
    "price": 49,
    "originalPrice": 69,
    "image": "https://templatemo.com/screenshots/full-template-491-flat.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-491-flat.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_491_flat.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Flat ووفر عشرات الساعات من التطوير.",
    "rating": 4.5,
    "reviews": 205,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "492",
    "title": "App Starter",
    "category": "Portfolio",
    "price": 59,
    "originalPrice": 79,
    "image": "https://templatemo.com/screenshots/full-template-492-app-starter.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-492-app-starter.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_492_app_starter.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب App Starter ووفر عشرات الساعات من التطوير.",
    "rating": 4.6,
    "reviews": 212,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "493",
    "title": "Snapshot",
    "category": "SaaS",
    "price": 69,
    "originalPrice": 89,
    "image": "https://templatemo.com/screenshots/full-template-493-snapshot.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-493-snapshot.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_493_snapshot.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Snapshot ووفر عشرات الساعات من التطوير.",
    "rating": 4.7,
    "reviews": 219,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "494",
    "title": "Motion",
    "category": "Landing",
    "price": 79,
    "originalPrice": 99,
    "image": "https://templatemo.com/screenshots/full-template-494-motion.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-494-motion.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_494_motion.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Motion ووفر عشرات الساعات من التطوير.",
    "rating": 4.8,
    "reviews": 226,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "495",
    "title": "Metro Fit",
    "category": "E-commerce",
    "price": 89,
    "originalPrice": 109,
    "image": "https://templatemo.com/screenshots/full-template-495-metro-fit.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-495-metro-fit.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_495_metro_fit.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Metro Fit ووفر عشرات الساعات من التطوير.",
    "rating": 4.9,
    "reviews": 233,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "496",
    "title": "Pipeline",
    "category": "Business",
    "price": 49,
    "originalPrice": 69,
    "image": "https://templatemo.com/screenshots/full-template-496-pipeline.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-496-pipeline.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_496_pipeline.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "حصري",
    "valueProposition": "استثمر في قالب Pipeline ووفر عشرات الساعات من التطوير.",
    "rating": 4.5,
    "reviews": 240,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "497",
    "title": "Upper",
    "category": "Portfolio",
    "price": 59,
    "originalPrice": 79,
    "image": "https://templatemo.com/screenshots/full-template-497-upper.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-497-upper.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_497_upper.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Upper ووفر عشرات الساعات من التطوير.",
    "rating": 4.6,
    "reviews": 247,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "498",
    "title": "Stimulus",
    "category": "SaaS",
    "price": 69,
    "originalPrice": 89,
    "image": "https://templatemo.com/screenshots/full-template-498-stimulus.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-498-stimulus.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_498_stimulus.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Stimulus ووفر عشرات الساعات من التطوير.",
    "rating": 4.7,
    "reviews": 254,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "499",
    "title": "Catalyst",
    "category": "Landing",
    "price": 79,
    "originalPrice": 99,
    "image": "https://templatemo.com/screenshots/full-template-499-catalyst.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-499-catalyst.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_499_catalyst.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Catalyst ووفر عشرات الساعات من التطوير.",
    "rating": 4.8,
    "reviews": 261,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "500",
    "title": "Fluid Gallery",
    "category": "E-commerce",
    "price": 89,
    "originalPrice": 109,
    "image": "https://templatemo.com/screenshots/full-template-500-fluid-gallery.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-500-fluid-gallery.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_500_fluid_gallery.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Fluid Gallery ووفر عشرات الساعات من التطوير.",
    "rating": 4.9,
    "reviews": 268,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "501",
    "title": "Neaty",
    "category": "Business",
    "price": 49,
    "originalPrice": 69,
    "image": "https://templatemo.com/screenshots/full-template-501-neaty.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-501-neaty.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_501_neaty.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Neaty ووفر عشرات الساعات من التطوير.",
    "rating": 4.5,
    "reviews": 275,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "502",
    "title": "Short",
    "category": "Portfolio",
    "price": 59,
    "originalPrice": 79,
    "image": "https://templatemo.com/screenshots/full-template-502-short.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-502-short.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_502_short.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Short ووفر عشرات الساعات من التطوير.",
    "rating": 4.6,
    "reviews": 282,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "503",
    "title": "Newline",
    "category": "SaaS",
    "price": 69,
    "originalPrice": 89,
    "image": "https://templatemo.com/screenshots/full-template-503-newline.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-503-newline.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_503_newline.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Newline ووفر عشرات الساعات من التطوير.",
    "rating": 4.7,
    "reviews": 289,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "504",
    "title": "Page One",
    "category": "Landing",
    "price": 79,
    "originalPrice": 99,
    "image": "https://templatemo.com/screenshots/full-template-504-page-one.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-504-page-one.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_504_page_one.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Page One ووفر عشرات الساعات من التطوير.",
    "rating": 4.8,
    "reviews": 296,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "505",
    "title": "Stacked",
    "category": "E-commerce",
    "price": 89,
    "originalPrice": 109,
    "image": "https://templatemo.com/screenshots/full-template-505-stacked.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-505-stacked.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_505_stacked.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Stacked ووفر عشرات الساعات من التطوير.",
    "rating": 4.9,
    "reviews": 303,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "506",
    "title": "Tinker",
    "category": "Business",
    "price": 49,
    "originalPrice": 69,
    "image": "https://templatemo.com/screenshots/full-template-506-tinker.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-506-tinker.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_506_tinker.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "حصري",
    "valueProposition": "استثمر في قالب Tinker ووفر عشرات الساعات من التطوير.",
    "rating": 4.5,
    "reviews": 310,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "507",
    "title": "Victory",
    "category": "Portfolio",
    "price": 59,
    "originalPrice": 79,
    "image": "https://templatemo.com/screenshots/full-template-507-victory.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-507-victory.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_507_victory.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Victory ووفر عشرات الساعات من التطوير.",
    "rating": 4.6,
    "reviews": 317,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "508",
    "title": "Power",
    "category": "SaaS",
    "price": 69,
    "originalPrice": 89,
    "image": "https://templatemo.com/screenshots/full-template-508-power.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-508-power.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_508_power.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Power ووفر عشرات الساعات من التطوير.",
    "rating": 4.7,
    "reviews": 324,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "509",
    "title": "Hydro",
    "category": "Landing",
    "price": 79,
    "originalPrice": 99,
    "image": "https://templatemo.com/screenshots/full-template-509-hydro.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-509-hydro.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_509_hydro.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Hydro ووفر عشرات الساعات من التطوير.",
    "rating": 4.8,
    "reviews": 331,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "510",
    "title": "Letter",
    "category": "E-commerce",
    "price": 89,
    "originalPrice": 109,
    "image": "https://templatemo.com/screenshots/full-template-510-letter.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-510-letter.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_510_letter.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Letter ووفر عشرات الساعات من التطوير.",
    "rating": 4.9,
    "reviews": 338,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "511",
    "title": "Journey",
    "category": "Business",
    "price": 49,
    "originalPrice": 69,
    "image": "https://templatemo.com/screenshots/full-template-511-journey.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-511-journey.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_511_journey.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Journey ووفر عشرات الساعات من التطوير.",
    "rating": 4.5,
    "reviews": 345,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "512",
    "title": "Moonlight",
    "category": "Portfolio",
    "price": 59,
    "originalPrice": 79,
    "image": "https://templatemo.com/screenshots/full-template-512-moonlight.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-512-moonlight.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_512_moonlight.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Moonlight ووفر عشرات الساعات من التطوير.",
    "rating": 4.6,
    "reviews": 352,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "513",
    "title": "Avalon",
    "category": "SaaS",
    "price": 69,
    "originalPrice": 89,
    "image": "https://templatemo.com/screenshots/full-template-513-avalon.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-513-avalon.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_513_avalon.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Avalon ووفر عشرات الساعات من التطوير.",
    "rating": 4.7,
    "reviews": 359,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "514",
    "title": "Magazee",
    "category": "Landing",
    "price": 79,
    "originalPrice": 99,
    "image": "https://templatemo.com/screenshots/full-template-514-magazee.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-514-magazee.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_514_magazee.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Magazee ووفر عشرات الساعات من التطوير.",
    "rating": 4.8,
    "reviews": 366,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "515",
    "title": "Eatery",
    "category": "E-commerce",
    "price": 89,
    "originalPrice": 109,
    "image": "https://templatemo.com/screenshots/full-template-515-eatery.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-515-eatery.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_515_eatery.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Eatery ووفر عشرات الساعات من التطوير.",
    "rating": 4.9,
    "reviews": 373,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "516",
    "title": "Known",
    "category": "Business",
    "price": 49,
    "originalPrice": 69,
    "image": "https://templatemo.com/screenshots/full-template-516-known.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-516-known.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_516_known.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "حصري",
    "valueProposition": "استثمر في قالب Known ووفر عشرات الساعات من التطوير.",
    "rating": 4.5,
    "reviews": 380,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "517",
    "title": "Timeless",
    "category": "Portfolio",
    "price": 59,
    "originalPrice": 79,
    "image": "https://templatemo.com/screenshots/full-template-517-timeless.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-517-timeless.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_517_timeless.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Timeless ووفر عشرات الساعات من التطوير.",
    "rating": 4.6,
    "reviews": 387,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "518",
    "title": "Sentra",
    "category": "SaaS",
    "price": 69,
    "originalPrice": 89,
    "image": "https://templatemo.com/screenshots/full-template-518-sentra.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-518-sentra.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_518_sentra.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Sentra ووفر عشرات الساعات من التطوير.",
    "rating": 4.7,
    "reviews": 394,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "519",
    "title": "Beauty",
    "category": "Landing",
    "price": 79,
    "originalPrice": 99,
    "image": "https://templatemo.com/screenshots/full-template-519-beauty.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-519-beauty.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_519_beauty.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Beauty ووفر عشرات الساعات من التطوير.",
    "rating": 4.8,
    "reviews": 401,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "520",
    "title": "Highway",
    "category": "E-commerce",
    "price": 89,
    "originalPrice": 109,
    "image": "https://templatemo.com/screenshots/full-template-520-highway.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-520-highway.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_520_highway.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Highway ووفر عشرات الساعات من التطوير.",
    "rating": 4.9,
    "reviews": 408,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "521",
    "title": "Get Ready",
    "category": "Business",
    "price": 49,
    "originalPrice": 69,
    "image": "https://templatemo.com/screenshots/full-template-521-get-ready.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-521-get-ready.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_521_get_ready.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Get Ready ووفر عشرات الساعات من التطوير.",
    "rating": 4.5,
    "reviews": 415,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "522",
    "title": "Venue",
    "category": "Portfolio",
    "price": 59,
    "originalPrice": 79,
    "image": "https://templatemo.com/screenshots/full-template-522-venue.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-522-venue.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_522_venue.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Venue ووفر عشرات الساعات من التطوير.",
    "rating": 4.6,
    "reviews": 422,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "523",
    "title": "Image Survey",
    "category": "SaaS",
    "price": 69,
    "originalPrice": 89,
    "image": "https://templatemo.com/screenshots/full-template-523-image-survey.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-523-image-survey.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_523_image_survey.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Image Survey ووفر عشرات الساعات من التطوير.",
    "rating": 4.7,
    "reviews": 429,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "524",
    "title": "Product Admin",
    "category": "Landing",
    "price": 79,
    "originalPrice": 99,
    "image": "https://templatemo.com/screenshots/full-template-524-product-admin.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-524-product-admin.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_524_product_admin.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Product Admin ووفر عشرات الساعات من التطوير.",
    "rating": 4.8,
    "reviews": 436,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "525",
    "title": "The Town",
    "category": "E-commerce",
    "price": 89,
    "originalPrice": 109,
    "image": "https://templatemo.com/screenshots/full-template-525-the-town.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-525-the-town.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_525_the_town.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب The Town ووفر عشرات الساعات من التطوير.",
    "rating": 4.9,
    "reviews": 443,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "527",
    "title": "Sided",
    "category": "Business",
    "price": 49,
    "originalPrice": 69,
    "image": "https://templatemo.com/screenshots/full-template-527-sided.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-527-sided.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_527_sided.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "حصري",
    "valueProposition": "استثمر في قالب Sided ووفر عشرات الساعات من التطوير.",
    "rating": 4.5,
    "reviews": 450,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "528",
    "title": "Elegance",
    "category": "Portfolio",
    "price": 59,
    "originalPrice": 79,
    "image": "https://templatemo.com/screenshots/full-template-528-elegance.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-528-elegance.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_528_elegance.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Elegance ووفر عشرات الساعات من التطوير.",
    "rating": 4.6,
    "reviews": 457,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "529",
    "title": "Ramayana",
    "category": "SaaS",
    "price": 69,
    "originalPrice": 89,
    "image": "https://templatemo.com/screenshots/full-template-529-ramayana.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-529-ramayana.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_529_ramayana.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Ramayana ووفر عشرات الساعات من التطوير.",
    "rating": 4.7,
    "reviews": 464,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "530",
    "title": "Mini Profile",
    "category": "Landing",
    "price": 79,
    "originalPrice": 99,
    "image": "https://templatemo.com/screenshots/full-template-530-mini-profile.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-530-mini-profile.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_530_mini_profile.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Mini Profile ووفر عشرات الساعات من التطوير.",
    "rating": 4.8,
    "reviews": 471,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "531",
    "title": "Reflux",
    "category": "E-commerce",
    "price": 89,
    "originalPrice": 109,
    "image": "https://templatemo.com/screenshots/full-template-531-reflux.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-531-reflux.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_531_reflux.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Reflux ووفر عشرات الساعات من التطوير.",
    "rating": 4.9,
    "reviews": 478,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "532",
    "title": "Next Level",
    "category": "Business",
    "price": 49,
    "originalPrice": 69,
    "image": "https://templatemo.com/screenshots/full-template-532-next-level.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-532-next-level.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_532_next_level.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Next Level ووفر عشرات الساعات من التطوير.",
    "rating": 4.5,
    "reviews": 485,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "533",
    "title": "Verticard",
    "category": "Portfolio",
    "price": 59,
    "originalPrice": 79,
    "image": "https://templatemo.com/screenshots/full-template-533-verticard.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-533-verticard.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_533_verticard.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Verticard ووفر عشرات الساعات من التطوير.",
    "rating": 4.6,
    "reviews": 492,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "534",
    "title": "Parallo",
    "category": "SaaS",
    "price": 69,
    "originalPrice": 89,
    "image": "https://templatemo.com/screenshots/full-template-534-parallo.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-534-parallo.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_534_parallo.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Parallo ووفر عشرات الساعات من التطوير.",
    "rating": 4.7,
    "reviews": 499,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "535",
    "title": "Softy Pinko",
    "category": "Landing",
    "price": 79,
    "originalPrice": 99,
    "image": "https://templatemo.com/screenshots/full-template-535-softy-pinko.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-535-softy-pinko.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_535_softy_pinko.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Softy Pinko ووفر عشرات الساعات من التطوير.",
    "rating": 4.8,
    "reviews": 506,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "536",
    "title": "Dream Pulse",
    "category": "E-commerce",
    "price": 89,
    "originalPrice": 109,
    "image": "https://templatemo.com/screenshots/full-template-536-dream-pulse.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-536-dream-pulse.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_536_dream_pulse.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Dream Pulse ووفر عشرات الساعات من التطوير.",
    "rating": 4.9,
    "reviews": 513,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "537",
    "title": "Art Factory",
    "category": "Business",
    "price": 49,
    "originalPrice": 69,
    "image": "https://templatemo.com/screenshots/full-template-537-art-factory.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-537-art-factory.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_537_art_factory.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "حصري",
    "valueProposition": "استثمر في قالب Art Factory ووفر عشرات الساعات من التطوير.",
    "rating": 4.5,
    "reviews": 520,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "538",
    "title": "Digital Trend",
    "category": "Portfolio",
    "price": 59,
    "originalPrice": 79,
    "image": "https://templatemo.com/screenshots/full-template-538-digital-trend.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-538-digital-trend.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_538_digital_trend.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Digital Trend ووفر عشرات الساعات من التطوير.",
    "rating": 4.6,
    "reviews": 527,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "539",
    "title": "Simple House",
    "category": "SaaS",
    "price": 69,
    "originalPrice": 89,
    "image": "https://templatemo.com/screenshots/full-template-539-simple-house.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-539-simple-house.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_539_simple_house.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Simple House ووفر عشرات الساعات من التطوير.",
    "rating": 4.7,
    "reviews": 534,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "540",
    "title": "Lava Landing Page",
    "category": "Landing",
    "price": 79,
    "originalPrice": 99,
    "image": "https://templatemo.com/screenshots/full-template-540-lava-landing-page.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-540-lava-landing-page.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_540_lava_landing_page.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Lava Landing Page ووفر عشرات الساعات من التطوير.",
    "rating": 4.8,
    "reviews": 541,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "542",
    "title": "New Vision",
    "category": "E-commerce",
    "price": 89,
    "originalPrice": 109,
    "image": "https://templatemo.com/screenshots/full-template-542-new-vision.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-542-new-vision.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_542_new_vision.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب New Vision ووفر عشرات الساعات من التطوير.",
    "rating": 4.9,
    "reviews": 548,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "543",
    "title": "Breezed",
    "category": "Business",
    "price": 49,
    "originalPrice": 69,
    "image": "https://templatemo.com/screenshots/full-template-543-breezed.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-543-breezed.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_543_breezed.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Breezed ووفر عشرات الساعات من التطوير.",
    "rating": 4.5,
    "reviews": 555,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "544",
    "title": "Comparto",
    "category": "Portfolio",
    "price": 59,
    "originalPrice": 79,
    "image": "https://templatemo.com/screenshots/full-template-544-comparto.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-544-comparto.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_544_comparto.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Comparto ووفر عشرات الساعات من التطوير.",
    "rating": 4.6,
    "reviews": 562,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "545",
    "title": "Finance Business",
    "category": "SaaS",
    "price": 69,
    "originalPrice": 89,
    "image": "https://templatemo.com/screenshots/full-template-545-finance-business.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-545-finance-business.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_545_finance_business.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Finance Business ووفر عشرات الساعات من التطوير.",
    "rating": 4.7,
    "reviews": 569,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "547",
    "title": "Real Dynamic",
    "category": "Landing",
    "price": 79,
    "originalPrice": 99,
    "image": "https://templatemo.com/screenshots/full-template-547-real-dynamic.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-547-real-dynamic.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_547_real_dynamic.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Real Dynamic ووفر عشرات الساعات من التطوير.",
    "rating": 4.8,
    "reviews": 576,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "549",
    "title": "Business Oriented",
    "category": "E-commerce",
    "price": 89,
    "originalPrice": 109,
    "image": "https://templatemo.com/screenshots/full-template-549-business-oriented.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-549-business-oriented.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_549_business_oriented.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Business Oriented ووفر عشرات الساعات من التطوير.",
    "rating": 4.9,
    "reviews": 583,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "550",
    "title": "Diagoona",
    "category": "Business",
    "price": 49,
    "originalPrice": 69,
    "image": "https://templatemo.com/screenshots/full-template-550-diagoona.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-550-diagoona.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_550_diagoona.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "حصري",
    "valueProposition": "استثمر في قالب Diagoona ووفر عشرات الساعات من التطوير.",
    "rating": 4.5,
    "reviews": 590,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "551",
    "title": "Stand Blog",
    "category": "Portfolio",
    "price": 59,
    "originalPrice": 79,
    "image": "https://templatemo.com/screenshots/full-template-551-stand-blog.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-551-stand-blog.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_551_stand_blog.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Stand Blog ووفر عشرات الساعات من التطوير.",
    "rating": 4.6,
    "reviews": 597,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "552",
    "title": "Video Catalog",
    "category": "SaaS",
    "price": 69,
    "originalPrice": 89,
    "image": "https://templatemo.com/screenshots/full-template-552-video-catalog.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-552-video-catalog.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_552_video_catalog.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Video Catalog ووفر عشرات الساعات من التطوير.",
    "rating": 4.7,
    "reviews": 604,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "553",
    "title": "Xtra Blog",
    "category": "Landing",
    "price": 79,
    "originalPrice": 99,
    "image": "https://templatemo.com/screenshots/full-template-553-xtra-blog.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-553-xtra-blog.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_553_xtra_blog.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Xtra Blog ووفر عشرات الساعات من التطوير.",
    "rating": 4.8,
    "reviews": 611,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "557",
    "title": "Grad School",
    "category": "E-commerce",
    "price": 89,
    "originalPrice": 109,
    "image": "https://templatemo.com/screenshots/full-template-557-grad-school.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-557-grad-school.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_557_grad_school.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Grad School ووفر عشرات الساعات من التطوير.",
    "rating": 4.9,
    "reviews": 618,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "558",
    "title": "Klassy Cafe",
    "category": "Business",
    "price": 49,
    "originalPrice": 69,
    "image": "https://templatemo.com/screenshots/full-template-558-klassy-cafe.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-558-klassy-cafe.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_558_klassy_cafe.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Klassy Cafe ووفر عشرات الساعات من التطوير.",
    "rating": 4.5,
    "reviews": 625,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "560",
    "title": "Astro Motion",
    "category": "Portfolio",
    "price": 59,
    "originalPrice": 79,
    "image": "https://templatemo.com/screenshots/full-template-560-astro-motion.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-560-astro-motion.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_560_astro_motion.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Astro Motion ووفر عشرات الساعات من التطوير.",
    "rating": 4.6,
    "reviews": 632,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "561",
    "title": "Purple Buzz",
    "category": "SaaS",
    "price": 69,
    "originalPrice": 89,
    "image": "https://templatemo.com/screenshots/full-template-561-purple-buzz.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-561-purple-buzz.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_561_purple_buzz.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Purple Buzz ووفر عشرات الساعات من التطوير.",
    "rating": 4.7,
    "reviews": 639,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "562",
    "title": "Space Dynamic",
    "category": "Landing",
    "price": 79,
    "originalPrice": 99,
    "image": "https://templatemo.com/screenshots/full-template-562-space-dynamic.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-562-space-dynamic.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_562_space_dynamic.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Space Dynamic ووفر عشرات الساعات من التطوير.",
    "rating": 4.8,
    "reviews": 646,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "563",
    "title": "Seo Dream",
    "category": "E-commerce",
    "price": 89,
    "originalPrice": 109,
    "image": "https://templatemo.com/screenshots/full-template-563-seo-dream.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-563-seo-dream.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_563_seo_dream.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Seo Dream ووفر عشرات الساعات من التطوير.",
    "rating": 4.9,
    "reviews": 653,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "564",
    "title": "Plot Listing",
    "category": "Business",
    "price": 49,
    "originalPrice": 69,
    "image": "https://templatemo.com/screenshots/full-template-564-plot-listing.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-564-plot-listing.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_564_plot_listing.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "حصري",
    "valueProposition": "استثمر في قالب Plot Listing ووفر عشرات الساعات من التطوير.",
    "rating": 4.5,
    "reviews": 660,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "565",
    "title": "Onix Digital",
    "category": "Portfolio",
    "price": 59,
    "originalPrice": 79,
    "image": "https://templatemo.com/screenshots/full-template-565-onix-digital.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-565-onix-digital.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_565_onix_digital.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Onix Digital ووفر عشرات الساعات من التطوير.",
    "rating": 4.6,
    "reviews": 667,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "567",
    "title": "Nomad Force",
    "category": "SaaS",
    "price": 69,
    "originalPrice": 89,
    "image": "https://templatemo.com/screenshots/full-template-567-nomad-force.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-567-nomad-force.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_567_nomad_force.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Nomad Force ووفر عشرات الساعات من التطوير.",
    "rating": 4.7,
    "reviews": 674,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "568",
    "title": "Digimedia",
    "category": "Landing",
    "price": 79,
    "originalPrice": 99,
    "image": "https://templatemo.com/screenshots/full-template-568-digimedia.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-568-digimedia.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_568_digimedia.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Digimedia ووفر عشرات الساعات من التطوير.",
    "rating": 4.8,
    "reviews": 681,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "569",
    "title": "Edu Meeting",
    "category": "E-commerce",
    "price": 89,
    "originalPrice": 109,
    "image": "https://templatemo.com/screenshots/full-template-569-edu-meeting.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-569-edu-meeting.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_569_edu_meeting.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Edu Meeting ووفر عشرات الساعات من التطوير.",
    "rating": 4.9,
    "reviews": 688,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "570",
    "title": "Chain App Dev",
    "category": "Business",
    "price": 49,
    "originalPrice": 69,
    "image": "https://templatemo.com/screenshots/full-template-570-chain-app-dev.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-570-chain-app-dev.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_570_chain_app_dev.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Chain App Dev ووفر عشرات الساعات من التطوير.",
    "rating": 4.5,
    "reviews": 695,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "571",
    "title": "Hexashop",
    "category": "Portfolio",
    "price": 59,
    "originalPrice": 79,
    "image": "https://templatemo.com/screenshots/full-template-571-hexashop.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-571-hexashop.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_571_hexashop.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Hexashop ووفر عشرات الساعات من التطوير.",
    "rating": 4.6,
    "reviews": 702,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "573",
    "title": "Eduwell",
    "category": "SaaS",
    "price": 69,
    "originalPrice": 89,
    "image": "https://templatemo.com/screenshots/full-template-573-eduwell.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-573-eduwell.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_573_eduwell.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Eduwell ووفر عشرات الساعات من التطوير.",
    "rating": 4.7,
    "reviews": 709,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "574",
    "title": "Mexant",
    "category": "Landing",
    "price": 79,
    "originalPrice": 99,
    "image": "https://templatemo.com/screenshots/full-template-574-mexant.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-574-mexant.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_574_mexant.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Mexant ووفر عشرات الساعات من التطوير.",
    "rating": 4.8,
    "reviews": 716,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "575",
    "title": "Leadership Event",
    "category": "E-commerce",
    "price": 89,
    "originalPrice": 109,
    "image": "https://templatemo.com/screenshots/full-template-575-leadership-event.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-575-leadership-event.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_575_leadership_event.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Leadership Event ووفر عشرات الساعات من التطوير.",
    "rating": 4.9,
    "reviews": 723,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "579",
    "title": "Cyborg Gaming",
    "category": "Business",
    "price": 49,
    "originalPrice": 69,
    "image": "https://templatemo.com/screenshots/full-template-579-cyborg-gaming.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-579-cyborg-gaming.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_579_cyborg_gaming (1).zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "حصري",
    "valueProposition": "استثمر في قالب Cyborg Gaming ووفر عشرات الساعات من التطوير.",
    "rating": 4.5,
    "reviews": 730,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "580",
    "title": "Woox Travel",
    "category": "Portfolio",
    "price": 59,
    "originalPrice": 79,
    "image": "https://templatemo.com/screenshots/full-template-580-woox-travel.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-580-woox-travel.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_580_woox_travel (2).zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Woox Travel ووفر عشرات الساعات من التطوير.",
    "rating": 4.6,
    "reviews": 737,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "581",
    "title": "Kind Heart Charity",
    "category": "SaaS",
    "price": 69,
    "originalPrice": 89,
    "image": "https://templatemo.com/screenshots/full-template-581-kind-heart-charity.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-581-kind-heart-charity.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_581_kind_heart_charity.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Kind Heart Charity ووفر عشرات الساعات من التطوير.",
    "rating": 4.7,
    "reviews": 744,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "582",
    "title": "Tale Seo Agency",
    "category": "Landing",
    "price": 79,
    "originalPrice": 99,
    "image": "https://templatemo.com/screenshots/full-template-582-tale-seo-agency.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-582-tale-seo-agency.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_582_tale_seo_agency.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Tale Seo Agency ووفر عشرات الساعات من التطوير.",
    "rating": 4.8,
    "reviews": 751,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "583",
    "title": "Festava Live",
    "category": "E-commerce",
    "price": 89,
    "originalPrice": 109,
    "image": "https://templatemo.com/screenshots/full-template-583-festava-live.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-583-festava-live.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_583_festava_live.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Festava Live ووفر عشرات الساعات من التطوير.",
    "rating": 4.9,
    "reviews": 758,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "584",
    "title": "Pod Talk",
    "category": "Business",
    "price": 49,
    "originalPrice": 69,
    "image": "https://templatemo.com/screenshots/full-template-584-pod-talk.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-584-pod-talk.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_584_pod_talk.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Pod Talk ووفر عشرات الساعات من التطوير.",
    "rating": 4.5,
    "reviews": 765,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "585",
    "title": "Barber Shop",
    "category": "Portfolio",
    "price": 59,
    "originalPrice": 79,
    "image": "https://templatemo.com/screenshots/full-template-585-barber-shop.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-585-barber-shop.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_585_barber_shop.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Barber Shop ووفر عشرات الساعات من التطوير.",
    "rating": 4.6,
    "reviews": 772,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "586",
    "title": "Scholar",
    "category": "SaaS",
    "price": 69,
    "originalPrice": 89,
    "image": "https://templatemo.com/screenshots/full-template-586-scholar.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-586-scholar.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_586_scholar.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Scholar ووفر عشرات الساعات من التطوير.",
    "rating": 4.7,
    "reviews": 779,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "587",
    "title": "Tiya Golf Club",
    "category": "Landing",
    "price": 79,
    "originalPrice": 99,
    "image": "https://templatemo.com/screenshots/full-template-587-tiya-golf-club.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-587-tiya-golf-club.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_587_tiya_golf_club.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Tiya Golf Club ووفر عشرات الساعات من التطوير.",
    "rating": 4.8,
    "reviews": 786,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "588",
    "title": "Ebook Landing",
    "category": "E-commerce",
    "price": 89,
    "originalPrice": 109,
    "image": "https://templatemo.com/screenshots/full-template-588-ebook-landing.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-588-ebook-landing.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_588_ebook_landing.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Ebook Landing ووفر عشرات الساعات من التطوير.",
    "rating": 4.9,
    "reviews": 793,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "589",
    "title": "Lugx Gaming",
    "category": "Business",
    "price": 49,
    "originalPrice": 69,
    "image": "https://templatemo.com/screenshots/full-template-589-lugx-gaming.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-589-lugx-gaming.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_589_lugx_gaming.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "حصري",
    "valueProposition": "استثمر في قالب Lugx Gaming ووفر عشرات الساعات من التطوير.",
    "rating": 4.5,
    "reviews": 800,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "590",
    "title": "Topic Listing",
    "category": "Portfolio",
    "price": 59,
    "originalPrice": 79,
    "image": "https://templatemo.com/screenshots/full-template-590-topic-listing.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-590-topic-listing.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_590_topic_listing.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Topic Listing ووفر عشرات الساعات من التطوير.",
    "rating": 4.6,
    "reviews": 807,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "591",
    "title": "Villa Agency",
    "category": "SaaS",
    "price": 69,
    "originalPrice": 89,
    "image": "https://templatemo.com/screenshots/full-template-591-villa-agency.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-591-villa-agency.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_591_villa_agency.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Villa Agency ووفر عشرات الساعات من التطوير.",
    "rating": 4.7,
    "reviews": 814,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "592",
    "title": "Glossy Touch",
    "category": "Landing",
    "price": 79,
    "originalPrice": 99,
    "image": "https://templatemo.com/screenshots/full-template-592-glossy-touch.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-592-glossy-touch.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_592_glossy_touch.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Glossy Touch ووفر عشرات الساعات من التطوير.",
    "rating": 4.8,
    "reviews": 821,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "593",
    "title": "Personal Shape",
    "category": "E-commerce",
    "price": 89,
    "originalPrice": 109,
    "image": "https://templatemo.com/screenshots/full-template-593-personal-shape.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-593-personal-shape.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_593_personal_shape.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Personal Shape ووفر عشرات الساعات من التطوير.",
    "rating": 4.9,
    "reviews": 828,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "594",
    "title": "Nexus Flow",
    "category": "Business",
    "price": 49,
    "originalPrice": 69,
    "image": "https://templatemo.com/screenshots/full-template-594-nexus-flow.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-594-nexus-flow.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_594_nexus_flow.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Nexus Flow ووفر عشرات الساعات من التطوير.",
    "rating": 4.5,
    "reviews": 835,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "595",
    "title": "3d Coverflow",
    "category": "Portfolio",
    "price": 59,
    "originalPrice": 79,
    "image": "https://templatemo.com/screenshots/full-template-595-3d-coverflow.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-595-3d-coverflow.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_595_3d_coverflow.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب 3d Coverflow ووفر عشرات الساعات من التطوير.",
    "rating": 4.6,
    "reviews": 842,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "596",
    "title": "Electric Xtra",
    "category": "SaaS",
    "price": 69,
    "originalPrice": 89,
    "image": "https://templatemo.com/screenshots/full-template-596-electric-xtra.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-596-electric-xtra.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_596_electric_xtra.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Electric Xtra ووفر عشرات الساعات من التطوير.",
    "rating": 4.7,
    "reviews": 849,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "597",
    "title": "Neural Glass",
    "category": "Landing",
    "price": 79,
    "originalPrice": 99,
    "image": "https://templatemo.com/screenshots/full-template-597-neural-glass.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-597-neural-glass.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_597_neural_glass.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Neural Glass ووفر عشرات الساعات من التطوير.",
    "rating": 4.8,
    "reviews": 856,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "598",
    "title": "Sleeky Pro",
    "category": "E-commerce",
    "price": 89,
    "originalPrice": 109,
    "image": "https://templatemo.com/screenshots/full-template-598-sleeky-pro.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-598-sleeky-pro.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_598_sleeky_pro.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Sleeky Pro ووفر عشرات الساعات من التطوير.",
    "rating": 4.9,
    "reviews": 863,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "599",
    "title": "Noir Fashion",
    "category": "Business",
    "price": 49,
    "originalPrice": 69,
    "image": "https://templatemo.com/screenshots/full-template-599-noir-fashion.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-599-noir-fashion.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_599_noir_fashion.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "حصري",
    "valueProposition": "استثمر في قالب Noir Fashion ووفر عشرات الساعات من التطوير.",
    "rating": 4.5,
    "reviews": 870,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "600",
    "title": "Prism Flux",
    "category": "Portfolio",
    "price": 59,
    "originalPrice": 79,
    "image": "https://templatemo.com/screenshots/full-template-600-prism-flux.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-600-prism-flux.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_600_prism_flux.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Prism Flux ووفر عشرات الساعات من التطوير.",
    "rating": 4.6,
    "reviews": 877,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "601",
    "title": "Chain Summit",
    "category": "SaaS",
    "price": 69,
    "originalPrice": 89,
    "image": "https://templatemo.com/screenshots/full-template-601-chain-summit.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-601-chain-summit.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_601_chain_summit.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Chain Summit ووفر عشرات الساعات من التطوير.",
    "rating": 4.7,
    "reviews": 884,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "602",
    "title": "Graph Page",
    "category": "Landing",
    "price": 79,
    "originalPrice": 99,
    "image": "https://templatemo.com/screenshots/full-template-602-graph-page.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-602-graph-page.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_602_graph_page.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Graph Page ووفر عشرات الساعات من التطوير.",
    "rating": 4.8,
    "reviews": 891,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "603",
    "title": "Nexaverse",
    "category": "E-commerce",
    "price": 89,
    "originalPrice": 109,
    "image": "https://templatemo.com/screenshots/full-template-603-nexaverse.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-603-nexaverse.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_603_nexaverse.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Nexaverse ووفر عشرات الساعات من التطوير.",
    "rating": 4.9,
    "reviews": 898,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "604",
    "title": "Christmas Piano",
    "category": "Business",
    "price": 49,
    "originalPrice": 69,
    "image": "https://templatemo.com/screenshots/full-template-604-christmas-piano.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-604-christmas-piano.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_604_christmas_piano.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Christmas Piano ووفر عشرات الساعات من التطوير.",
    "rating": 4.5,
    "reviews": 905,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "605",
    "title": "Xmas Countdown",
    "category": "Portfolio",
    "price": 59,
    "originalPrice": 79,
    "image": "https://templatemo.com/screenshots/full-template-605-xmas-countdown.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-605-xmas-countdown.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_605_xmas_countdown.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Xmas Countdown ووفر عشرات الساعات من التطوير.",
    "rating": 4.6,
    "reviews": 912,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "606",
    "title": "String Master",
    "category": "SaaS",
    "price": 69,
    "originalPrice": 89,
    "image": "https://templatemo.com/screenshots/full-template-606-string-master.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-606-string-master.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_606_string_master.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب String Master ووفر عشرات الساعات من التطوير.",
    "rating": 4.7,
    "reviews": 919,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "607",
    "title": "Glass Admin",
    "category": "Landing",
    "price": 79,
    "originalPrice": 99,
    "image": "https://templatemo.com/screenshots/full-template-607-glass-admin.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-607-glass-admin.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_607_glass_admin.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Glass Admin ووفر عشرات الساعات من التطوير.",
    "rating": 4.8,
    "reviews": 926,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "608",
    "title": "Daynight Admin",
    "category": "E-commerce",
    "price": 89,
    "originalPrice": 109,
    "image": "https://templatemo.com/screenshots/full-template-608-daynight-admin.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-608-daynight-admin.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_608_daynight_admin.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Daynight Admin ووفر عشرات الساعات من التطوير.",
    "rating": 4.9,
    "reviews": 933,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "609",
    "title": "Crypto Vault",
    "category": "Business",
    "price": 49,
    "originalPrice": 69,
    "image": "https://templatemo.com/screenshots/full-template-609-crypto-vault.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-609-crypto-vault.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_609_crypto_vault.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "حصري",
    "valueProposition": "استثمر في قالب Crypto Vault ووفر عشرات الساعات من التطوير.",
    "rating": 4.5,
    "reviews": 940,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "610",
    "title": "Aurum Gold",
    "category": "Portfolio",
    "price": 59,
    "originalPrice": 79,
    "image": "https://templatemo.com/screenshots/full-template-610-aurum-gold.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-610-aurum-gold.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_610_aurum_gold.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Aurum Gold ووفر عشرات الساعات من التطوير.",
    "rating": 4.6,
    "reviews": 947,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "611",
    "title": "Maison Doree",
    "category": "SaaS",
    "price": 69,
    "originalPrice": 89,
    "image": "https://templatemo.com/screenshots/full-template-611-maison-doree.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-611-maison-doree.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_611_maison_doree.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Maison Doree ووفر عشرات الساعات من التطوير.",
    "rating": 4.7,
    "reviews": 954,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "612",
    "title": "Parallax Starter",
    "category": "Landing",
    "price": 79,
    "originalPrice": 99,
    "image": "https://templatemo.com/screenshots/full-template-612-parallax-starter.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-612-parallax-starter.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_612_parallax_starter.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Parallax Starter ووفر عشرات الساعات من التطوير.",
    "rating": 4.8,
    "reviews": 961,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "613",
    "title": "Frost Bakery",
    "category": "E-commerce",
    "price": 89,
    "originalPrice": 109,
    "image": "https://templatemo.com/screenshots/full-template-613-frost-bakery.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-613-frost-bakery.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_613_frost_bakery (1).zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Frost Bakery ووفر عشرات الساعات من التطوير.",
    "rating": 4.9,
    "reviews": 968,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "614",
    "title": "Quantix Saas",
    "category": "Business",
    "price": 49,
    "originalPrice": 69,
    "image": "https://templatemo.com/screenshots/full-template-614-quantix-saas.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-614-quantix-saas.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_614_quantix_saas.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Quantix Saas ووفر عشرات الساعات من التطوير.",
    "rating": 4.5,
    "reviews": 975,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "615",
    "title": "Amber Folio",
    "category": "Portfolio",
    "price": 59,
    "originalPrice": 79,
    "image": "https://templatemo.com/screenshots/full-template-615-amber-folio.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-615-amber-folio.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_615_amber_folio.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Amber Folio ووفر عشرات الساعات من التطوير.",
    "rating": 4.6,
    "reviews": 982,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "616",
    "title": "Split Index",
    "category": "SaaS",
    "price": 69,
    "originalPrice": 89,
    "image": "https://templatemo.com/screenshots/full-template-616-split-index.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-616-split-index.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_616_split_index.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Split Index ووفر عشرات الساعات من التطوير.",
    "rating": 4.7,
    "reviews": 989,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  },
  {
    "id": "617",
    "title": "Pixel Forge",
    "category": "Landing",
    "price": 79,
    "originalPrice": 99,
    "image": "https://templatemo.com/screenshots/full-template-617-pixel-forge.jpg",
    "thumbnail": "https://templatemo.com/screenshots/full-template-617-pixel-forge.jpg",
    "demoUrl": "#",
    "downloadUrl": "/templates/templatemo_617_pixel_forge.zip",
    "isNiche": false,
    "aiFeatures": [],
    "badge": "",
    "valueProposition": "استثمر في قالب Pixel Forge ووفر عشرات الساعات من التطوير.",
    "rating": 4.8,
    "reviews": 996,
    "author": "Kyrosys Vault",
    "description": "قالب ممتاز وحصري مصمم بعناية فائقة لتلبية أعلى معايير الجودة."
  }
];


export const ALL_TEMPLATES = TEMPLATES;

export const CATEGORIES = [
  { id: 'all', label: 'النبض العام' },
  { id: 'ai-startup', label: 'الذكاء الاصطناعي والسيادة' },
  { id: 'saas', label: 'نظم SaaS الاحترافية' },
  { id: 'landing', label: 'صفحات الهبوط المطلقة' },
  { id: 'ecommerce', label: 'التجارة العابرة للحدود' },
  { id: 'portfolio', label: 'سجلات النخبة' },
  { id: 'dashboard', label: 'مراكز التحكم المركزية' },
  { id: 'luxury-gold', label: 'الذهب والرفاهية العالية' },
  { id: 'agency', label: 'وكالات النفوذ الرقمي' },
  { id: 'medical', label: 'الصحة والبروتوكولات الطبية' },
  { id: 'realestate', label: 'الأراضي والمنشآت الحصرية' },
];

export const ASSET_CLASSES = [
  { id: 'OMEGA', label: 'أوميغا (المطلق)', color: 'text-gold' },
  { id: 'S-CLASS', label: 'فئة S (نخبة)', color: 'text-pearl' },
  { id: 'A-CLASS', label: 'فئة A (احترافي)', color: 'text-slate-300' },
  { id: 'VOID', label: 'الفراغ (توليدي)', color: 'text-indigo-400' },
];

